from pypinyin import pinyin, lazy_pinyin
def chinese_to_pinyin(text):
    # 使用lazy_pinyin获取拼音，不包含声调
    pinyin_list = lazy_pinyin(text)
    # 将拼音以空格分隔并返回
    return ' '.join(pinyin_list)

def kanji_to_pinyin_main(txt):
    result = chinese_to_pinyin(txt)
    return result

def load_conversion_rules():
    """Load the conversion rules for Pinyin to Japanese Kana."""
    return {
        "a": "あ",
        "ai": "あい",
        "ang": "あん",
        "ao": "あう",
        "ba": "ば",
        "bai": "ばい",
        "bang": "ばん",
        "bao": "ばう",
        "bei": "べい",
        "beng": "べん",
        "bi": "び",
        "bia": "びあ",
        "biang": "びあん",
        "biao": "びあう",
        "bie": "びえ",
        "bing": "びん",
        "bo": "ぼ",
        "bu": "ぶ",
        "ca": "つぁ",
        "cai": "つぁい",
        "cang": "つぁん",
        "cao": "つぁう",
        "ceng": "つぇん",
        "ci": "つぃ",
        "cong": "つぉん",
        "cou": "つぉう",
        "cu": "つ",
        "cuan": "つあん",
        "cui": "つえい",
        "cuo": "つお",
        "da": "だ",
        "dai": "だい",
        "dang": "だん",
        "dao": "だう",
        "dei": "でい",
        "deng": "でん",
        "di": "でぃ",
        "dia": "でぃあ",
        "dian": "でぃあん",
        "diao": "でぃあう",
        "die": "でぃえ",
        "ding": "でぃん",
        "diu": "でゅよ",
        "dong": "どん",
        "dou": "どう",
        "du": "どぅ",
        "duan": "どぅあん",
        "dui": "どぅえい",
        "dun": "どぅん",
        "duo": "どぅお",
        "ei": "えい",
        "eng": "えん",
        "fa": "ふぁ",
        "fang": "ふぁん",
        "fei": "ふぇい",
        "feng": "ふぇん",
        "fiao": "ふぃあう",
        "fo": "ふぉ",
        "fou": "ふぉう",
        "fu": "ふ",
        "ga": "が",
        "gai": "がい",
        "gang": "がん",
        "gao": "がう",
        "gei": "げい",
        "geng": "げん",
        "gong": "ごん",
        "gou": "ごう",
        "gu": "ぐ",
        "gua": "ぐあ",
        "guai": "ぐあい",
        "guang": "ぐあん",
        "gui": "ぐえい",
        "gun": "ぐん",
        "guo": "ぐお",
        "ha": "は",
        "hai": "はい",
        "hang": "はん",
        "hao": "はう",
        "hei": "へい",
        "heng": "へん",
        "hong": "ほん",
        "hou": "ほう",
        "ji": "じ",
        "jia": "じあ",
        "jiang": "じあん",
        "jiao": "じあう",
        "jie": "じえ",
        "jing": "じん",
        "jiong": "じよん",
        "jiu": "じよ",
        "ju": "じゅゆ",
        "jue": "じゅゆえ",
        "ka": "か",
        "kai": "かい",
        "kang": "かん",
        "kao": "かう",
        "kei": "けい",
        "keng": "けん",
        "kong": "こん",
        "kou": "こう",
        "ku": "くク",
        "kua": "くあ",
        "kuai": "くあい",
        "kuang": "くあん",
        "kui": "くえい",
        "kun": "くん",
        "kuo": "くお",
        "la": "ら",
        "lai": "らい",
        "lang": "らん",
        "lao": "らう",
        "lei": "れい",
        "leng": "れん",
        "li": "り",
        "lia": "りあ",
        "liang": "りあん",
        "liao": "りあう",
        "lie": "りえ",
        "ling": "りん",
        "liu": "りよ",
        "lo": "ろ",
        "long": "ろん",
        "lou": "ろう",
        "lu": "る",
        "luang": "るあん",
        "lun": "るん",
        "luo": "るお",
        "ma": "ま",
        "mai": "まい",
        "mang": "まん",
        "mao": "まう",
        "mei": "めい",
        "meng": "めん",
        "mi": "み",
        "mia": "みあ",
        "mian": "みあん",
        "miao": "みあう",
        "mie": "みえ",
        "ming": "みん",
        "miu": "みよ",
        "mo": "も",
        "mou": "もう",
        "mu": "む",
        "na": "な",
        "nai": "ない",
        "nang": "なん",
        "nao": "なう",
        "nei": "ねい",
        "neng": "ねん",
        "ni": "に",
        "niang": "にあん",
        "niao": "にあう",
        "nie": "にえ",
        "ning": "にん",
        "niu": "によ",
        "nong": "のん",
        "nou": "のう",
        "nu": "ぬ",
        "nuang": "ぬん",
        "nun": "ぬん",
        "nuo": "ぬお",
        "o": "お",
        "ou": "おう",
        "pa": "ぱ",
        "pai": "ぱい",
        "pang": "ぱん",
        "pao": "ぱう",
        "pei": "ぺい",
        "peng": "ぺん",
        "pi": "ぴ",
        "pia": "ぴあ",
        "pian": "ぴあん",
        "piao": "ぴあう",
        "pie": "ぴえ",
        "ping": "ぴん",
        "po": "ぽ",
        "pou": "ぽう",
        "pu": "ぷ",
        "qi": "ち",
        "qia": "ちあ",
        "qiang": "ちあん",
        "qiao": "ちあう",
        "qie": "ちえ",
        "qing": "ちん",
        "qiong": "ちよん",
        "qiu": "ちよ",
        "qu": "ちゅゆ",
        "que": "ちゅゆえ",
        "sa": "た",
        "sai": "たい",
        "sang": "たん",
        "sao": "たう",
        "seng": "せん",
        "si": "スィ",
        "song": "そん",
        "sou": "そう",
        "su": "す",
        "suan": "すあん",
        "sui": "すえい",
        "suo": "すお",
        "ta": "た",
        "tai": "たい",
        "tang": "たん",
        "tao": "たう",
        "teng": "てん",
        "ti": "てぃ",
        "tian": "てぃあん",
        "tiao": "てぃあう",
        "tie": "てぃえ",
        "ting": "てぃん",
        "tong": "とん",
        "tou": "とう",
        "tu": "とぅ",
        "tuan": "とぅあん",
        "tui": "とぅえい",
        "tun": "とぅん",
        "tuo": "とぅお",
        "wa": "わ",
        "wai": "わい",
        "wang": "わん",
        "wei": "うい",
        "wen": "うえん",
        "weng": "うん",
        "wo": "を",
        "wu": "う",
        "xi": "し",
        "xia": "しあ",
        "xiang": "しあん",
        "xiao": "しあう",
        "xie": "しえ",
        "xing": "しん",
        "xiong": "しよん",
        "xiu": "しよ",
        "xu": "しゅゆ",
        "xue": "しゅゆえ",
        "ya": "や",
        "yang": "やん",
        "yao": "やう",
        "ye": "いえ",
        "yi": "い",
        "ying": "いん",
        "yong": "よん",
        "you": "よ",
        "yu": "ゆ",
        "yuang": "ゆあん",
        "yue": "ゆえ",
        "yun": "ゆん",
        "za": "ざ",
        "zai": "ざい",
        "zang": "ざん",
        "zao": "ざう",
        "zei": "ぜい",
        "zeng": "ぜん",
        "zi": "ズィ",
        "zong": "ぞん",
        "zou": "ぞう",
        "zu": "ず",
        "zuan": "ずあん",
        "zui": "ずえい",
        "zuo": "ずお"
    }


def pinyin_to_kana(pinyin, conversion_rules):
    """Convert Pinyin to Japanese Kana based on rules.

    Args:
        pinyin (str): The input Pinyin string.
        conversion_rules (dict): A dictionary of Pinyin to Kana mappings.

    Returns:
        str: The converted Kana string.
    """
    words = pinyin.split()
    kana_result = []

    for word in words:
        if word in conversion_rules:
            kana_result.append(conversion_rules[word])
        else:
            kana_result.append(f"[{word}]")  # 标记为未匹配

    return " ".join(kana_result)

if __name__ == "__main__":
    print("伪日本语生成器")
    conversion_rules = load_conversion_rules()

    while True:
        kanji = input("请输入中文汉字 (输入 'exit' 退出): ")
        if kanji.lower() == "exit":
            print("退出程序。")
            break

        kana_output = pinyin_to_kana(kanji_to_pinyin_main(kanji), conversion_rules)
        
        print(f"假名输出: {kana_output}")
